// Natture pigment data - generated from pigment-data-natture.json

// Arcocem Basic pigment densities (g/mL) for gram-to-mL conversion
export const PIGMENT_DENSITIES: Record<string, number> = {
  'BLANCO': 2.10,
  'NEGRO': 1.56,
  'AMARILLO': 1.62,
  'VERDE': 1.91,
  'ROJO NARANJA': 1.17,
  'AZUL': 1.07,
  'AMARILLO VAINILLA': 1.62, // becsült érték (AMARILLO alapján)
  'NEGRO HUMO': 1.56,        // becsült érték (NEGRO alapján)
  'ROJO INTENSO': 1.17,      // becsült érték (ROJO NARANJA alapján)
};

// Arcocem Basic product prices, sizes and Shoprenter SKUs
export const PIGMENT_PRODUCTS: Record<string, { name: string; options: { liters: number; price: number; sku: string }[] }> = {
  'AMARILLO': { name: 'Arcocem Basic Amarillo', options: [{ liters: 0.5, price: 20545, sku: 'TT04503' }, { liters: 1, price: 30385, sku: 'TT04003' }] },
  'AZUL': { name: 'Arcocem Basic Azul', options: [{ liters: 0.5, price: 46075, sku: 'TT04506' }, { liters: 1, price: 70580, sku: 'TT04006' }] },
  'BLANCO': { name: 'Arcocem Basic Blanco', options: [{ liters: 0.5, price: 23170, sku: 'TT04502' }, { liters: 1, price: 34505, sku: 'TT04002' }] },
  'NEGRO': { name: 'Arcocem Basic Negro', options: [{ liters: 0.5, price: 17155, sku: 'TT04501' }, { liters: 1, price: 25495, sku: 'TT04001' }] },
  'ROJO NARANJA': { name: 'Arcocem Basic Rojo Naranja', options: [{ liters: 0.5, price: 20545, sku: 'TT04505' }, { liters: 1, price: 30385, sku: 'TT04005' }] },
  'VERDE': { name: 'Arcocem Basic Verde', options: [{ liters: 0.5, price: 32945, sku: 'TT04504' }, { liters: 1, price: 49930, sku: 'TT04004' }] },
  'AMARILLO VAINILLA': { name: 'Arcocem Basic Amarillo Vainilla', options: [{ liters: 1, price: 26995, sku: 'TT04608' }] },
  'NEGRO HUMO': { name: 'Arcocem Basic Negro Humo', options: [{ liters: 1, price: 25420, sku: 'TT04612' }] },
  'ROJO INTENSO': { name: 'Arcocem Basic Rojo Intenso', options: [{ liters: 1, price: 40160, sku: 'TT04611' }] },
};

// Sealer key to pigment recipe type mapping
// null means no color selection available for that sealer
export const SEALER_TO_PIGMENT_TYPE: Record<string, string | null> = {
  'onecoat_matt': 'WT',
  'onecoat_selyem': 'WT',
  'onecoat_fenyes': 'WT',
  'dragon_matt': 'WT',
  'dragon_selyem': 'WT',
  'dragon_fenyes': 'WT',
  'top100_matt': 'TOP100',
  'top100_fenyes': 'TOP100',
  'toppro_lassukotesu': null,
  'toppro_gyorskotesu': null,
};

type PigmentRecipe = { basePigment: string; gramsPerKg: number }[];
type ColorRecipes = Record<string, PigmentRecipe>;
type GrainRecipes = Record<string, ColorRecipes>;

// All available Natture colors (48 colors)
export const NATTURE_COLORS: string[] = ['ACERO', 'ADRA', 'AZUL PROFUNDO', 'BLANCO', 'BLANCO ROTO', 'BLUSH', 'BONE', 'BREEZE', 'CAFE', 'CAIRO', 'CALABAZA', 'CEMENTO', 'CHAMPAGNE', 'CLAY', 'COBRE', 'CORAL', 'COTTON', 'DESERT TAN', 'EUCALYPTUS', 'GINGER', 'HIMALAYA', 'INDIA', 'JADE', 'KALAHARI', 'KHAKI', 'LIQUEN', 'MARRON', 'MOJAVE', 'MOON', 'MOSS', 'NEBULA', 'PAPYRUS', 'PEARL GREY', 'PERLA', 'PINK', 'PIZARRA', 'PLOMO', 'PORCELAIN', 'PURE BLACK', 'RAFFIA', 'SAHARA', 'SALMON', 'SAMOS', 'SAND', 'SHALE GREY', 'SPIKE', 'UNIVERSE', 'WASABI'];

// Color HEX codes for color swatches
export const NATTURE_COLOR_HEX: Record<string, string> = {
  'ACERO': '#8d8077',
  'ADRA': '#9a8877',
  'AZUL PROFUNDO': '#739ab2',
  'BLANCO': '#efede8',
  'BLANCO ROTO': '#ece4d3',
  'BLUSH': '#e0d0c8',
  'BONE': '#ddceb6',
  'BREEZE': '#a9bfc4',
  'CAFE': '#d0b08a',
  'CAIRO': '#cdb89a',
  'CALABAZA': '#c96b29',
  'CEMENTO': '#c6c0ad',
  'CHAMPAGNE': '#e7d0ae',
  'CLAY': '#d2b79f',
  'COBRE': '#825747',
  'CORAL': '#efb5a2',
  'COTTON': '#fdf5df',
  'DESERT TAN': '#baa46c',
  'EUCALYPTUS': '#b2c5b4',
  'GINGER': '#eabe6a',
  'HIMALAYA': '#716a5d',
  'INDIA': '#e9cfa2',
  'JADE': '#8ab9c4',
  'KALAHARI': '#be996a',
  'KHAKI': '#b6b18b',
  'LIQUEN': '#ccc5ac',
  'MARRON': '#8f7460',
  'MOJAVE': '#dbb686',
  'MOON': '#a8a598',
  'MOSS': '#d2d9ca',
  'NEBULA': '#e9e4d0',
  'PAPYRUS': '#bcae9c',
  'PEARL GREY': '#ccc1ae',
  'PERLA': '#cec4b6',
  'PINK': '#e4c4bd',
  'PIZARRA': '#6f6964',
  'PLOMO': '#7b776e',
  'PORCELAIN': '#e1d7bb',
  'PURE BLACK': '#2b2b29',
  'RAFFIA': '#bea98d',
  'SAHARA': '#e4d2b3',
  'SALMON': '#f2bc8f',
  'SAMOS': '#7a6d5d',
  'SAND': '#b6a485',
  'SHALE GREY': '#817b70',
  'SPIKE': '#c2b3a1',
  'UNIVERSE': '#c3beb6',
  'WASABI': '#d2c490',
};

export const NATTURE_PIGMENT_RECIPES: Record<string, GrainRecipes> = {
  "WT": {
    "s": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 8.53 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.55 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 5.2 }, { basePigment: "NEGRO", gramsPerKg: 12 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 40 }, { basePigment: "NEGRO", gramsPerKg: 3 }, { basePigment: "VERDE", gramsPerKg: 4 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 53.4 }],
      "BLANCO ROTO": [{ basePigment: "AMARILLO", gramsPerKg: 0.02 }, { basePigment: "NEGRO", gramsPerKg: 0.01 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.004 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.104 }, { basePigment: "VERDE", gramsPerKg: 0.22 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 1.1 }, { basePigment: "NEGRO", gramsPerKg: 0.8 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.18 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 4.5 }, { basePigment: "NEGRO", gramsPerKg: 0.13 }, { basePigment: "VERDE", gramsPerKg: 0.68 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 5.5 }, { basePigment: "NEGRO", gramsPerKg: 4.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5.6 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 2.542 }, { basePigment: "NEGRO", gramsPerKg: 1.8 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.99 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 94.43 }, { basePigment: "NEGRO", gramsPerKg: 1.27 }, { basePigment: "ROJO NARANJA", gramsPerKg: 54.35 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 5 }, { basePigment: "VERDE", gramsPerKg: 2.84 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 1.71 }, { basePigment: "NEGRO", gramsPerKg: 0.457 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 1.5 }, { basePigment: "NEGRO", gramsPerKg: 1.65 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.5 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 23 }, { basePigment: "NEGRO", gramsPerKg: 15 }, { basePigment: "ROJO NARANJA", gramsPerKg: 40 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 9.4 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.7 }, { basePigment: "NEGRO", gramsPerKg: 0.2 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.25 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 16.5 }, { basePigment: "NEGRO", gramsPerKg: 7.63 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5.53 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 28.6 }, { basePigment: "AZUL", gramsPerKg: 5.72 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 18 }, { basePigment: "NEGRO", gramsPerKg: 0.05 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.2 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.45 }, { basePigment: "NEGRO", gramsPerKg: 10 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 3.1 }, { basePigment: "NEGRO", gramsPerKg: 0.25 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.15 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 43 }, { basePigment: "AZUL", gramsPerKg: 25 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 27.48 }, { basePigment: "NEGRO", gramsPerKg: 4.68 }, { basePigment: "ROJO NARANJA", gramsPerKg: 7.1 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 2 }, { basePigment: "NEGRO", gramsPerKg: 1.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1 }, { basePigment: "VERDE", gramsPerKg: 8 }],
      "LIQUEN": [{ basePigment: "AMARILLO", gramsPerKg: 0.25 }, { basePigment: "NEGRO", gramsPerKg: 1 }, { basePigment: "VERDE", gramsPerKg: 0.46 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 2.8 }, { basePigment: "NEGRO", gramsPerKg: 25 }, { basePigment: "ROJO NARANJA", gramsPerKg: 9.6 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 4.5 }, { basePigment: "NEGRO", gramsPerKg: 1.4 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.1 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 1.5 }, { basePigment: "NEGRO", gramsPerKg: 5.15 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.71 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 4.1 }, { basePigment: "AZUL", gramsPerKg: 1.7 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.86 }, { basePigment: "BLANCO", gramsPerKg: 22.17 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.15 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 1.691 }, { basePigment: "NEGRO", gramsPerKg: 3.14 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.3 }, { basePigment: "NEGRO", gramsPerKg: 2.2 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.38 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 1.2 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.6 }, { basePigment: "BLANCO", gramsPerKg: 7 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.4 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 51.7 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 40 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.65 }, { basePigment: "NEGRO", gramsPerKg: 0.32 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.025 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 54.49 }, { basePigment: "NEGRO HUMO", gramsPerKg: 38.67 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 3 }, { basePigment: "NEGRO", gramsPerKg: 5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 2 }, { basePigment: "NEGRO", gramsPerKg: 1.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.8 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 6 }, { basePigment: "NEGRO", gramsPerKg: 1 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.6 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 7 }, { basePigment: "NEGRO", gramsPerKg: 13.2 }, { basePigment: "ROJO NARANJA", gramsPerKg: 4.5 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 5.5 }, { basePigment: "NEGRO", gramsPerKg: 3.66 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.9 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 1.8 }, { basePigment: "NEGRO", gramsPerKg: 25 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.7 }, { basePigment: "NEGRO", gramsPerKg: 1.6 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.7 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 3 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 4 }, { basePigment: "VERDE", gramsPerKg: 5 }],
    },
    "m": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 11 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 3.64 }, { basePigment: "NEGRO", gramsPerKg: 8.39 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.4 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 23.6 }, { basePigment: "BLANCO", gramsPerKg: 1.33 }, { basePigment: "NEGRO", gramsPerKg: 0.33 }, { basePigment: "VERDE", gramsPerKg: 3.54 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 30 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.07 }, { basePigment: "VERDE", gramsPerKg: 0.15 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.77 }, { basePigment: "NEGRO", gramsPerKg: 0.56 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.13 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 3.15 }, { basePigment: "NEGRO", gramsPerKg: 0.09 }, { basePigment: "VERDE", gramsPerKg: 0.48 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 2.95 }, { basePigment: "NEGRO", gramsPerKg: 2.21 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.39 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 1.78 }, { basePigment: "NEGRO", gramsPerKg: 1.26 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.4 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 38 }, { basePigment: "NEGRO", gramsPerKg: 0.38 }, { basePigment: "ROJO NARANJA", gramsPerKg: 23.2 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 2.6 }, { basePigment: "VERDE", gramsPerKg: 1.2 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 1.2 }, { basePigment: "NEGRO", gramsPerKg: 0.32 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 1.05 }, { basePigment: "NEGRO", gramsPerKg: 1.15 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.75 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 8.85 }, { basePigment: "NEGRO", gramsPerKg: 4.43 }, { basePigment: "ROJO NARANJA", gramsPerKg: 13.57 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.35 }, { basePigment: "ROJO NARANJA", gramsPerKg: 6.57 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.49 }, { basePigment: "NEGRO", gramsPerKg: 0.14 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.17 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 11.49 }, { basePigment: "NEGRO", gramsPerKg: 5.51 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.09 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 20 }, { basePigment: "AZUL", gramsPerKg: 4 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 12.59 }, { basePigment: "NEGRO", gramsPerKg: 0.03 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.84 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.152 }, { basePigment: "NEGRO", gramsPerKg: 4.9 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 2.17 }, { basePigment: "NEGRO", gramsPerKg: 0.17 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.1 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 16.23 }, { basePigment: "AZUL", gramsPerKg: 29.5 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 12.4 }, { basePigment: "NEGRO", gramsPerKg: 1.78 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.14 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 1.4 }, { basePigment: "NEGRO", gramsPerKg: 1.05 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.7 }, { basePigment: "VERDE", gramsPerKg: 5.59 }],
      "LIQUEN": [{ basePigment: "NEGRO", gramsPerKg: 0.54 }, { basePigment: "VERDE", gramsPerKg: 0.45 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 0.89 }, { basePigment: "NEGRO", gramsPerKg: 8.85 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.69 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 2.95 }, { basePigment: "NEGRO", gramsPerKg: 0.59 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.77 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 1.05 }, { basePigment: "NEGRO", gramsPerKg: 3.6 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.5 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 2.87 }, { basePigment: "AZUL", gramsPerKg: 1.19 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.6 }, { basePigment: "BLANCO", gramsPerKg: 11.2 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.1 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 1.19 }, { basePigment: "NEGRO", gramsPerKg: 2.2 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.21 }, { basePigment: "NEGRO", gramsPerKg: 1.54 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.27 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.84 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.42 }, { basePigment: "BLANCO", gramsPerKg: 4.9 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.28 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 28 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 20.65 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.95 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.45 }, { basePigment: "NEGRO", gramsPerKg: 0.22 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.02 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 36 }, { basePigment: "NEGRO HUMO", gramsPerKg: 27.04 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 2.1 }, { basePigment: "NEGRO", gramsPerKg: 3.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.4 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 0.52 }, { basePigment: "NEGRO", gramsPerKg: 0.3 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.59 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 4.2 }, { basePigment: "NEGRO", gramsPerKg: 0.7 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.52 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 4.9 }, { basePigment: "NEGRO", gramsPerKg: 9.23 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.15 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 3.85 }, { basePigment: "NEGRO", gramsPerKg: 2.56 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.63 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 0.31 }, { basePigment: "NEGRO", gramsPerKg: 9.94 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.49 }, { basePigment: "NEGRO", gramsPerKg: 1.12 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.49 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 2.1 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 2.8 }, { basePigment: "VERDE", gramsPerKg: 3.5 }],
    },
    "l": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 9.33 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.92 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 3.08 }, { basePigment: "NEGRO", gramsPerKg: 7.12 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.19 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 20.01 }, { basePigment: "BLANCO", gramsPerKg: 1.13 }, { basePigment: "NEGRO", gramsPerKg: 0.28 }, { basePigment: "VERDE", gramsPerKg: 3 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 25.44 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.06 }, { basePigment: "VERDE", gramsPerKg: 0.13 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.65 }, { basePigment: "NEGRO", gramsPerKg: 0.47 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.11 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 2.67 }, { basePigment: "NEGRO", gramsPerKg: 0.08 }, { basePigment: "VERDE", gramsPerKg: 0.4 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 2.5 }, { basePigment: "NEGRO", gramsPerKg: 1.88 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.88 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 1.51 }, { basePigment: "NEGRO", gramsPerKg: 1.07 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.18 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 32.224 }, { basePigment: "NEGRO", gramsPerKg: 0.322 }, { basePigment: "ROJO NARANJA", gramsPerKg: 19.674 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 2.205 }, { basePigment: "VERDE", gramsPerKg: 1.018 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 1.01 }, { basePigment: "NEGRO", gramsPerKg: 0.27 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 0.89 }, { basePigment: "NEGRO", gramsPerKg: 0.98 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.48 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 7.5 }, { basePigment: "NEGRO", gramsPerKg: 3.75 }, { basePigment: "ROJO NARANJA", gramsPerKg: 11.51 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.3 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5.57 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.42 }, { basePigment: "NEGRO", gramsPerKg: 0.12 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.15 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 9.75 }, { basePigment: "NEGRO", gramsPerKg: 4.67 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.62 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 16.96 }, { basePigment: "AZUL", gramsPerKg: 3.39 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 10.67 }, { basePigment: "NEGRO", gramsPerKg: 0.03 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.71 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.129 }, { basePigment: "NEGRO", gramsPerKg: 4.16 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.84 }, { basePigment: "NEGRO", gramsPerKg: 0.15 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.09 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 13.76 }, { basePigment: "AZUL", gramsPerKg: 25.02 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 10.52 }, { basePigment: "NEGRO", gramsPerKg: 1.51 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.66 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 1.19 }, { basePigment: "NEGRO", gramsPerKg: 0.89 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.59 }, { basePigment: "VERDE", gramsPerKg: 4.74 }],
      "LIQUEN": [{ basePigment: "NEGRO", gramsPerKg: 0.46 }, { basePigment: "VERDE", gramsPerKg: 0.38 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 0.75 }, { basePigment: "NEGRO", gramsPerKg: 7.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.13 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 2.5 }, { basePigment: "NEGRO", gramsPerKg: 0.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.65 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 0.89 }, { basePigment: "NEGRO", gramsPerKg: 3.05 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.42 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 2.43 }, { basePigment: "AZUL", gramsPerKg: 1.01 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.51 }, { basePigment: "BLANCO", gramsPerKg: 13.15 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.09 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 1 }, { basePigment: "NEGRO", gramsPerKg: 1.86 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.18 }, { basePigment: "NEGRO", gramsPerKg: 1.3 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.23 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.71 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.36 }, { basePigment: "BLANCO", gramsPerKg: 4.15 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.24 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 23.74 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 17.51 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.5 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.39 }, { basePigment: "NEGRO", gramsPerKg: 0.19 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.01 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 32.31 }, { basePigment: "NEGRO HUMO", gramsPerKg: 22.93 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.78 }, { basePigment: "NEGRO", gramsPerKg: 2.97 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.19 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 0.44 }, { basePigment: "NEGRO", gramsPerKg: 0.25 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.5 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 3.56 }, { basePigment: "NEGRO", gramsPerKg: 0.59 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.13 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 4.15 }, { basePigment: "NEGRO", gramsPerKg: 7.83 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.67 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 3.26 }, { basePigment: "NEGRO", gramsPerKg: 2.17 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.53 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 0.26 }, { basePigment: "NEGRO", gramsPerKg: 8.43 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.42 }, { basePigment: "NEGRO", gramsPerKg: 0.95 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.42 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 1.78 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 2.37 }, { basePigment: "VERDE", gramsPerKg: 2.97 }],
    },
    "xl": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 7.92 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.78 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 2.62 }, { basePigment: "NEGRO", gramsPerKg: 6.04 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.01 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 16.99 }, { basePigment: "BLANCO", gramsPerKg: 0.96 }, { basePigment: "NEGRO", gramsPerKg: 0.23 }, { basePigment: "VERDE", gramsPerKg: 2.55 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 21.6 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.05 }, { basePigment: "VERDE", gramsPerKg: 0.11 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.55 }, { basePigment: "NEGRO", gramsPerKg: 0.4 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.09 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 2.27 }, { basePigment: "NEGRO", gramsPerKg: 0.07 }, { basePigment: "VERDE", gramsPerKg: 0.34 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 2.12 }, { basePigment: "NEGRO", gramsPerKg: 1.59 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.44 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 1.28 }, { basePigment: "NEGRO", gramsPerKg: 0.91 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 27.36 }, { basePigment: "NEGRO", gramsPerKg: 0.274 }, { basePigment: "ROJO NARANJA", gramsPerKg: 16.704 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 1.872 }, { basePigment: "VERDE", gramsPerKg: 0.864 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 0.86 }, { basePigment: "NEGRO", gramsPerKg: 0.23 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 0.76 }, { basePigment: "NEGRO", gramsPerKg: 0.83 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.26 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 6.37 }, { basePigment: "NEGRO", gramsPerKg: 3.19 }, { basePigment: "ROJO NARANJA", gramsPerKg: 9.77 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.25 }, { basePigment: "ROJO NARANJA", gramsPerKg: 4.73 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.35 }, { basePigment: "NEGRO", gramsPerKg: 0.1 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.13 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 8.27 }, { basePigment: "NEGRO", gramsPerKg: 3.97 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.23 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 14.4 }, { basePigment: "AZUL", gramsPerKg: 2.88 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 9.06 }, { basePigment: "NEGRO", gramsPerKg: 0.03 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.6 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.109 }, { basePigment: "NEGRO", gramsPerKg: 3.53 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.56 }, { basePigment: "NEGRO", gramsPerKg: 0.13 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.08 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 11.68 }, { basePigment: "AZUL", gramsPerKg: 21.24 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 8.93 }, { basePigment: "NEGRO", gramsPerKg: 1.28 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.26 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 1.01 }, { basePigment: "NEGRO", gramsPerKg: 0.76 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.5 }, { basePigment: "VERDE", gramsPerKg: 4.03 }],
      "LIQUEN": [{ basePigment: "NEGRO", gramsPerKg: 0.39 }, { basePigment: "VERDE", gramsPerKg: 0.32 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 0.64 }, { basePigment: "NEGRO", gramsPerKg: 6.37 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.66 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 2.12 }, { basePigment: "NEGRO", gramsPerKg: 0.42 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.55 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 0.75 }, { basePigment: "NEGRO", gramsPerKg: 2.59 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.36 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 2.06 }, { basePigment: "AZUL", gramsPerKg: 0.86 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.43 }, { basePigment: "BLANCO", gramsPerKg: 11.16 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.07 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 0.85 }, { basePigment: "NEGRO", gramsPerKg: 1.58 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.15 }, { basePigment: "NEGRO", gramsPerKg: 1.11 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.19 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.6 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.3 }, { basePigment: "BLANCO", gramsPerKg: 3.52 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.2 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 20.16 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 14.87 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.12 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.33 }, { basePigment: "NEGRO", gramsPerKg: 0.16 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.01 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 27.44 }, { basePigment: "NEGRO HUMO", gramsPerKg: 19.47 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.51 }, { basePigment: "NEGRO", gramsPerKg: 2.52 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.01 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 0.37 }, { basePigment: "NEGRO", gramsPerKg: 0.21 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.42 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 3.02 }, { basePigment: "NEGRO", gramsPerKg: 0.5 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.81 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 3.52 }, { basePigment: "NEGRO", gramsPerKg: 6.65 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.27 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 2.77 }, { basePigment: "NEGRO", gramsPerKg: 1.84 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.45 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 0.22 }, { basePigment: "NEGRO", gramsPerKg: 7.16 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.35 }, { basePigment: "NEGRO", gramsPerKg: 0.81 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.35 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 1.51 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 2.01 }, { basePigment: "VERDE", gramsPerKg: 2.52 }],
    },
  },
  "TOP100": {
    "s": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 4.77 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.87 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 2.91 }, { basePigment: "NEGRO", gramsPerKg: 6.71 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.12 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 22.38 }, { basePigment: "NEGRO", gramsPerKg: 1.68 }, { basePigment: "VERDE", gramsPerKg: 2.24 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 29.87 }],
      "BLANCO ROTO": [{ basePigment: "AMARILLO", gramsPerKg: 0.011 }, { basePigment: "NEGRO", gramsPerKg: 0.006 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.002 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.06 }, { basePigment: "VERDE", gramsPerKg: 0.12 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.62 }, { basePigment: "NEGRO", gramsPerKg: 0.45 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.1 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 2.52 }, { basePigment: "NEGRO", gramsPerKg: 0.07 }, { basePigment: "VERDE", gramsPerKg: 0.38 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 3.08 }, { basePigment: "NEGRO", gramsPerKg: 2.52 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.13 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 1.42 }, { basePigment: "NEGRO", gramsPerKg: 1.01 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.11 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 52.826 }, { basePigment: "NEGRO", gramsPerKg: 0.708 }, { basePigment: "ROJO NARANJA", gramsPerKg: 30.406 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 2.8 }, { basePigment: "VERDE", gramsPerKg: 1.59 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 0.96 }, { basePigment: "NEGRO", gramsPerKg: 0.26 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 0.84 }, { basePigment: "NEGRO", gramsPerKg: 0.92 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.4 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 12.87 }, { basePigment: "NEGRO", gramsPerKg: 8.39 }, { basePigment: "ROJO NARANJA", gramsPerKg: 22.38 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.28 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5.26 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.39 }, { basePigment: "NEGRO", gramsPerKg: 0.11 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.14 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 9.23 }, { basePigment: "NEGRO", gramsPerKg: 4.27 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.1 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 16 }, { basePigment: "AZUL", gramsPerKg: 3.2 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 10.07 }, { basePigment: "NEGRO", gramsPerKg: 0.03 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.67 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.252 }, { basePigment: "NEGRO", gramsPerKg: 5.59 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.73 }, { basePigment: "NEGRO", gramsPerKg: 0.14 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.08 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 24.06 }, { basePigment: "AZUL", gramsPerKg: 13.99 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 15.38 }, { basePigment: "NEGRO", gramsPerKg: 2.62 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.97 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 1.12 }, { basePigment: "NEGRO", gramsPerKg: 0.84 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.56 }, { basePigment: "VERDE", gramsPerKg: 4.48 }],
      "LIQUEN": [{ basePigment: "AMARILLO", gramsPerKg: 0.14 }, { basePigment: "NEGRO", gramsPerKg: 0.56 }, { basePigment: "VERDE", gramsPerKg: 0.26 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 1.57 }, { basePigment: "NEGRO", gramsPerKg: 13.99 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5.37 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 2.52 }, { basePigment: "NEGRO", gramsPerKg: 0.78 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.62 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 0.84 }, { basePigment: "NEGRO", gramsPerKg: 2.88 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.4 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 2.29 }, { basePigment: "AZUL", gramsPerKg: 0.95 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.48 }, { basePigment: "BLANCO", gramsPerKg: 12.4 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.08 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 0.95 }, { basePigment: "NEGRO", gramsPerKg: 1.76 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.17 }, { basePigment: "NEGRO", gramsPerKg: 1.23 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.21 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.67 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.34 }, { basePigment: "BLANCO", gramsPerKg: 3.92 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.22 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 28.92 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 22.38 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.8 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.36 }, { basePigment: "NEGRO", gramsPerKg: 0.18 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.01 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 30.48 }, { basePigment: "NEGRO HUMO", gramsPerKg: 21.63 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.68 }, { basePigment: "NEGRO", gramsPerKg: 2.8 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.12 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 1.12 }, { basePigment: "NEGRO", gramsPerKg: 0.84 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.01 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 3.36 }, { basePigment: "NEGRO", gramsPerKg: 0.56 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.01 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 3.92 }, { basePigment: "NEGRO", gramsPerKg: 7.38 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.52 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 3.08 }, { basePigment: "NEGRO", gramsPerKg: 2.05 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.5 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 1.01 }, { basePigment: "NEGRO", gramsPerKg: 13.99 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.39 }, { basePigment: "NEGRO", gramsPerKg: 0.9 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.39 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 1.68 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 2.24 }, { basePigment: "VERDE", gramsPerKg: 2.8 }],
    },
    "m": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 6.05 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.6 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 2 }, { basePigment: "NEGRO", gramsPerKg: 4.62 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.77 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 12.98 }, { basePigment: "BLANCO", gramsPerKg: 0.73 }, { basePigment: "NEGRO", gramsPerKg: 0.18 }, { basePigment: "VERDE", gramsPerKg: 1.95 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 16.5 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.04 }, { basePigment: "VERDE", gramsPerKg: 0.08 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.42 }, { basePigment: "NEGRO", gramsPerKg: 0.31 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.07 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 1.73 }, { basePigment: "NEGRO", gramsPerKg: 0.05 }, { basePigment: "VERDE", gramsPerKg: 0.26 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 1.62 }, { basePigment: "NEGRO", gramsPerKg: 1.22 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.87 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 0.98 }, { basePigment: "NEGRO", gramsPerKg: 0.69 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.77 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 20.9 }, { basePigment: "NEGRO", gramsPerKg: 0.209 }, { basePigment: "ROJO NARANJA", gramsPerKg: 12.76 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 1.43 }, { basePigment: "VERDE", gramsPerKg: 0.66 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 0.66 }, { basePigment: "NEGRO", gramsPerKg: 0.18 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 0.58 }, { basePigment: "NEGRO", gramsPerKg: 0.63 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.96 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 4.87 }, { basePigment: "NEGRO", gramsPerKg: 2.43 }, { basePigment: "ROJO NARANJA", gramsPerKg: 7.46 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.19 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.62 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.27 }, { basePigment: "NEGRO", gramsPerKg: 0.08 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.1 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 6.32 }, { basePigment: "NEGRO", gramsPerKg: 3.03 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.7 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 11 }, { basePigment: "AZUL", gramsPerKg: 2.2 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 6.92 }, { basePigment: "NEGRO", gramsPerKg: 0.02 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.46 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.08 }, { basePigment: "NEGRO", gramsPerKg: 2.7 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.19 }, { basePigment: "NEGRO", gramsPerKg: 0.1 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.06 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 8.92 }, { basePigment: "AZUL", gramsPerKg: 16.23 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 6.82 }, { basePigment: "NEGRO", gramsPerKg: 0.98 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.73 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 0.77 }, { basePigment: "NEGRO", gramsPerKg: 0.58 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.38 }, { basePigment: "VERDE", gramsPerKg: 3.08 }],
      "LIQUEN": [{ basePigment: "NEGRO", gramsPerKg: 0.3 }, { basePigment: "VERDE", gramsPerKg: 0.25 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 0.49 }, { basePigment: "NEGRO", gramsPerKg: 4.87 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.03 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 1.62 }, { basePigment: "NEGRO", gramsPerKg: 0.32 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.42 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 0.58 }, { basePigment: "NEGRO", gramsPerKg: 1.98 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.27 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 1.58 }, { basePigment: "AZUL", gramsPerKg: 0.65 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.33 }, { basePigment: "BLANCO", gramsPerKg: 8.53 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.06 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 0.65 }, { basePigment: "NEGRO", gramsPerKg: 1.21 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.12 }, { basePigment: "NEGRO", gramsPerKg: 0.85 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.15 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.46 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.23 }, { basePigment: "BLANCO", gramsPerKg: 2.69 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.15 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 15.4 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 11.36 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.62 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.25 }, { basePigment: "NEGRO", gramsPerKg: 0.12 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.01 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 20.96 }, { basePigment: "NEGRO HUMO", gramsPerKg: 14.87 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.15 }, { basePigment: "NEGRO", gramsPerKg: 1.92 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.77 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 0.28 }, { basePigment: "NEGRO", gramsPerKg: 0.16 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.32 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 2.31 }, { basePigment: "NEGRO", gramsPerKg: 0.38 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.38 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 2.69 }, { basePigment: "NEGRO", gramsPerKg: 5.08 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.73 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 2.12 }, { basePigment: "NEGRO", gramsPerKg: 1.41 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.35 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 0.17 }, { basePigment: "NEGRO", gramsPerKg: 5.47 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.27 }, { basePigment: "NEGRO", gramsPerKg: 0.62 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.27 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 1.15 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 1.54 }, { basePigment: "VERDE", gramsPerKg: 1.92 }],
    },
    "l": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 5.17 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.51 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 1.71 }, { basePigment: "NEGRO", gramsPerKg: 3.94 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.66 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 11.09 }, { basePigment: "BLANCO", gramsPerKg: 0.62 }, { basePigment: "NEGRO", gramsPerKg: 0.15 }, { basePigment: "VERDE", gramsPerKg: 1.66 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 14.1 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.03 }, { basePigment: "VERDE", gramsPerKg: 0.07 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.36 }, { basePigment: "NEGRO", gramsPerKg: 0.26 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.06 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 1.48 }, { basePigment: "NEGRO", gramsPerKg: 0.04 }, { basePigment: "VERDE", gramsPerKg: 0.22 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 1.39 }, { basePigment: "NEGRO", gramsPerKg: 1.04 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.59 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 0.84 }, { basePigment: "NEGRO", gramsPerKg: 0.59 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.65 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 17.86 }, { basePigment: "NEGRO", gramsPerKg: 0.179 }, { basePigment: "ROJO NARANJA", gramsPerKg: 10.904 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 1.222 }, { basePigment: "VERDE", gramsPerKg: 0.564 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 0.56 }, { basePigment: "NEGRO", gramsPerKg: 0.15 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 0.49 }, { basePigment: "NEGRO", gramsPerKg: 0.54 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.82 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 4.16 }, { basePigment: "NEGRO", gramsPerKg: 2.08 }, { basePigment: "ROJO NARANJA", gramsPerKg: 6.38 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.16 }, { basePigment: "ROJO NARANJA", gramsPerKg: 3.09 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.23 }, { basePigment: "NEGRO", gramsPerKg: 0.07 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.08 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 5.4 }, { basePigment: "NEGRO", gramsPerKg: 2.59 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.45 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 9.4 }, { basePigment: "AZUL", gramsPerKg: 1.88 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 5.92 }, { basePigment: "NEGRO", gramsPerKg: 0.02 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.39 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.07 }, { basePigment: "NEGRO", gramsPerKg: 2.3 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 1.02 }, { basePigment: "NEGRO", gramsPerKg: 0.08 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.05 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 7.63 }, { basePigment: "AZUL", gramsPerKg: 13.87 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 5.83 }, { basePigment: "NEGRO", gramsPerKg: 0.84 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.48 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 0.66 }, { basePigment: "NEGRO", gramsPerKg: 0.49 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.33 }, { basePigment: "VERDE", gramsPerKg: 2.63 }],
      "LIQUEN": [{ basePigment: "NEGRO", gramsPerKg: 0.26 }, { basePigment: "VERDE", gramsPerKg: 0.21 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 0.42 }, { basePigment: "NEGRO", gramsPerKg: 4.16 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.73 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 1.39 }, { basePigment: "NEGRO", gramsPerKg: 0.28 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.36 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 0.49 }, { basePigment: "NEGRO", gramsPerKg: 1.69 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.23 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 1.35 }, { basePigment: "AZUL", gramsPerKg: 0.56 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.28 }, { basePigment: "BLANCO", gramsPerKg: 7.29 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.05 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 0.56 }, { basePigment: "NEGRO", gramsPerKg: 1.03 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.1 }, { basePigment: "NEGRO", gramsPerKg: 0.72 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.12 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.39 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.2 }, { basePigment: "BLANCO", gramsPerKg: 2.3 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.13 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 13.16 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 9.71 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.39 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.21 }, { basePigment: "NEGRO", gramsPerKg: 0.11 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.01 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 17.91 }, { basePigment: "NEGRO HUMO", gramsPerKg: 12.71 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 0.99 }, { basePigment: "NEGRO", gramsPerKg: 1.64 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.66 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 0.24 }, { basePigment: "NEGRO", gramsPerKg: 0.14 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.28 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 1.97 }, { basePigment: "NEGRO", gramsPerKg: 0.33 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.18 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 2.3 }, { basePigment: "NEGRO", gramsPerKg: 4.34 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.48 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 1.81 }, { basePigment: "NEGRO", gramsPerKg: 1.2 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.3 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 0.15 }, { basePigment: "NEGRO", gramsPerKg: 4.67 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.23 }, { basePigment: "NEGRO", gramsPerKg: 0.53 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.23 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 0.99 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 1.31 }, { basePigment: "VERDE", gramsPerKg: 1.64 }],
    },
    "xl": {
      "ACERO": [{ basePigment: "NEGRO", gramsPerKg: 4.57 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.45 }],
      "ADRA": [{ basePigment: "AMARILLO", gramsPerKg: 1.51 }, { basePigment: "NEGRO", gramsPerKg: 3.48 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.58 }],
      "AZUL PROFUNDO": [{ basePigment: "AZUL", gramsPerKg: 9.79 }, { basePigment: "BLANCO", gramsPerKg: 0.55 }, { basePigment: "NEGRO", gramsPerKg: 0.13 }, { basePigment: "VERDE", gramsPerKg: 1.47 }],
      "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 12.45 }],
      "BLUSH": [{ basePigment: "ROJO INTENSO", gramsPerKg: 0.03 }, { basePigment: "VERDE", gramsPerKg: 0.06 }],
      "BONE": [{ basePigment: "AMARILLO", gramsPerKg: 0.32 }, { basePigment: "NEGRO", gramsPerKg: 0.23 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.05 }],
      "BREEZE": [{ basePigment: "AZUL", gramsPerKg: 1.31 }, { basePigment: "NEGRO", gramsPerKg: 0.04 }, { basePigment: "VERDE", gramsPerKg: 0.2 }],
      "CAFE": [{ basePigment: "AMARILLO", gramsPerKg: 1.22 }, { basePigment: "NEGRO", gramsPerKg: 0.92 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.41 }],
      "CAIRO": [{ basePigment: "AMARILLO", gramsPerKg: 0.74 }, { basePigment: "NEGRO", gramsPerKg: 0.52 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.58 }],
      "CALABAZA": [{ basePigment: "AMARILLO", gramsPerKg: 15.77 }, { basePigment: "NEGRO", gramsPerKg: 0.158 }, { basePigment: "ROJO NARANJA", gramsPerKg: 9.628 }],
      "CEMENTO": [{ basePigment: "NEGRO", gramsPerKg: 1.079 }, { basePigment: "VERDE", gramsPerKg: 0.498 }],
      "CHAMPAGNE": [{ basePigment: "AMARILLO", gramsPerKg: 0.5 }, { basePigment: "NEGRO", gramsPerKg: 0.13 }],
      "CLAY": [{ basePigment: "AMARILLO", gramsPerKg: 0.44 }, { basePigment: "NEGRO", gramsPerKg: 0.48 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.73 }],
      "COBRE": [{ basePigment: "AMARILLO", gramsPerKg: 3.67 }, { basePigment: "NEGRO", gramsPerKg: 1.84 }, { basePigment: "ROJO NARANJA", gramsPerKg: 5.63 }],
      "CORAL": [{ basePigment: "AMARILLO", gramsPerKg: 0.15 }, { basePigment: "ROJO NARANJA", gramsPerKg: 2.73 }],
      "COTTON": [{ basePigment: "AMARILLO", gramsPerKg: 0.2 }, { basePigment: "NEGRO", gramsPerKg: 0.06 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.07 }],
      "DESERT TAN": [{ basePigment: "AMARILLO", gramsPerKg: 4.77 }, { basePigment: "NEGRO", gramsPerKg: 2.29 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.28 }],
      "EUCALYPTUS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 8.3 }, { basePigment: "AZUL", gramsPerKg: 1.66 }],
      "GINGER": [{ basePigment: "AMARILLO", gramsPerKg: 5.22 }, { basePigment: "NEGRO", gramsPerKg: 0.01 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.35 }],
      "HIMALAYA": [{ basePigment: "AZUL", gramsPerKg: 0.06 }, { basePigment: "NEGRO", gramsPerKg: 2.03 }],
      "INDIA": [{ basePigment: "AMARILLO", gramsPerKg: 0.9 }, { basePigment: "NEGRO", gramsPerKg: 0.07 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.04 }],
      "JADE": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 6.73 }, { basePigment: "AZUL", gramsPerKg: 12.24 }],
      "KALAHARI": [{ basePigment: "AMARILLO", gramsPerKg: 5.15 }, { basePigment: "NEGRO", gramsPerKg: 0.74 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.3 }],
      "KHAKI": [{ basePigment: "AMARILLO", gramsPerKg: 0.58 }, { basePigment: "NEGRO", gramsPerKg: 0.44 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.29 }, { basePigment: "VERDE", gramsPerKg: 2.32 }],
      "LIQUEN": [{ basePigment: "NEGRO", gramsPerKg: 0.23 }, { basePigment: "VERDE", gramsPerKg: 0.19 }],
      "MARRON": [{ basePigment: "AMARILLO", gramsPerKg: 0.37 }, { basePigment: "NEGRO", gramsPerKg: 3.67 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.53 }],
      "MOJAVE": [{ basePigment: "AMARILLO", gramsPerKg: 1.22 }, { basePigment: "NEGRO", gramsPerKg: 0.24 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.32 }],
      "MOON": [{ basePigment: "AZUL", gramsPerKg: 0.43 }, { basePigment: "NEGRO", gramsPerKg: 1.49 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.21 }],
      "MOSS": [{ basePigment: "AMARILLO VAINILLA", gramsPerKg: 1.19 }, { basePigment: "AZUL", gramsPerKg: 0.49 }],
      "NEBULA": [{ basePigment: "AMARILLO", gramsPerKg: 0.25 }, { basePigment: "BLANCO", gramsPerKg: 6.43 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.04 }],
      "PAPYRUS": [{ basePigment: "AMARILLO", gramsPerKg: 0.49 }, { basePigment: "NEGRO", gramsPerKg: 0.91 }],
      "PEARL GREY": [{ basePigment: "AMARILLO", gramsPerKg: 0.09 }, { basePigment: "NEGRO", gramsPerKg: 0.64 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.11 }],
      "PERLA": [{ basePigment: "NEGRO", gramsPerKg: 0.35 }],
      "PINK": [{ basePigment: "AMARILLO", gramsPerKg: 0.17 }, { basePigment: "BLANCO", gramsPerKg: 2.03 }, { basePigment: "ROJO INTENSO", gramsPerKg: 0.12 }],
      "PIZARRA": [{ basePigment: "NEGRO", gramsPerKg: 11.62 }],
      "PLOMO": [{ basePigment: "NEGRO", gramsPerKg: 8.57 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.22 }],
      "PORCELAIN": [{ basePigment: "AMARILLO", gramsPerKg: 0.19 }, { basePigment: "NEGRO", gramsPerKg: 0.09 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.01 }],
      "PURE BLACK": [{ basePigment: "NEGRO", gramsPerKg: 15.81 }, { basePigment: "NEGRO HUMO", gramsPerKg: 11.22 }],
      "RAFFIA": [{ basePigment: "AMARILLO", gramsPerKg: 0.87 }, { basePigment: "NEGRO", gramsPerKg: 1.45 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.58 }],
      "SAHARA": [{ basePigment: "AMARILLO", gramsPerKg: 0.21 }, { basePigment: "NEGRO", gramsPerKg: 0.12 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.24 }],
      "SALMON": [{ basePigment: "AMARILLO", gramsPerKg: 1.74 }, { basePigment: "NEGRO", gramsPerKg: 0.29 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.04 }],
      "SAMOS": [{ basePigment: "AMARILLO", gramsPerKg: 2.03 }, { basePigment: "NEGRO", gramsPerKg: 3.83 }, { basePigment: "ROJO NARANJA", gramsPerKg: 1.31 }],
      "SAND": [{ basePigment: "AMARILLO", gramsPerKg: 1.6 }, { basePigment: "NEGRO", gramsPerKg: 1.06 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.26 }],
      "SHALE GREY": [{ basePigment: "AZUL", gramsPerKg: 0.13 }, { basePigment: "NEGRO", gramsPerKg: 4.13 }],
      "SPIKE": [{ basePigment: "AMARILLO", gramsPerKg: 0.2 }, { basePigment: "NEGRO", gramsPerKg: 0.46 }, { basePigment: "ROJO NARANJA", gramsPerKg: 0.2 }],
      "UNIVERSE": [{ basePigment: "NEGRO", gramsPerKg: 0.87 }],
      "WASABI": [{ basePigment: "AMARILLO", gramsPerKg: 1.16 }, { basePigment: "VERDE", gramsPerKg: 1.45 }],
    },
  },
};

// Atlanttic (Pool) pigment recipes - only XL gets BLANCO pigment
export const ATLANTTIC_PIGMENT_RECIPES: Record<string, ColorRecipes> = {
  "xl": {
    "BLANCO": [{ basePigment: "BLANCO", gramsPerKg: 1.072 }]
  }
};
